# Environment settings
show_progress: True
gpu_id: 0
seed: 2022
use_gpu: True
state: INFO
reproducibility: True
data_path: 'dataset'
#checkpoint_dir: 'saved/saved_PFCN_PMF'
checkpoint_dir: 'saved/saved_LastFM-100K'
dataset: LastFM-100K
save_dataset: False
save_dataloaders: False

# Data settings
item_inter_num_interval: "[1,inf)"
user_inter_num_interval: "[1,inf)"
sst_attr_list: ["gender", "age"]
load_col:
  inter: [user_id,item_id,rating]
  user: [user_id,gender,age]
#  item: [item_id]

fill_nan: True
normalize_all: True

# model config
# model: PFCN_PMF
# model: ItemKNN

# training settings
epochs: 1000
train_batch_size: 2048
# train_batch_size: 4096
learner: adam
# learning_rate: 0.0001
# eval_step: 1
# stopping_step: 10
neg_sampling: 
  uniform: 1
# weight_decay: 0.00001

# evalution settings
eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: uni100
# metrics: ["NDCG", "Recall", "Hit", "MRR", "Precision", "AveragePopularity", "ItemCoverage", "GiniIndex", "DifferentialFairness", 
#         "NonParityUnfairness", "ValueUnfairness", "AbsoluteUnfairness", "UnderUnfairness", "OverUnfairness", "TailPercentage", "NDCG_sep", "NDCG_sub"]
metrics: ["NDCG", "Recall", "Hit", "MRR", "Precision", "NDCG_sep_Latest_beta", "NDCG_sub_Latest_beta"]
valid_metric: NDCG@10
topk: [5, 10, 15]
# dataset indicator
BR: [0]
ML: [0]
LF: [1]
#
popularity_ratio: 0.1
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4
